package dev.martinloeseth.watchedapp.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val GreenPrimary = Color(0xFF386A20)
val GreenOnPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFFB7F397)
val GreenOnPrimaryContainer = Color(0xFF042100)
val GreenSecondary = Color(0xFF55624C)
val GreenOnSecondary = Color(0xFFFFFFFF)
val GreenSecondaryContainer = Color(0xFFD8E7CB)
val GreenOnSecondaryContainer = Color(0xFF131F0D)
val GreenTertiary = Color(0xFF386667)
val GreenOnTertiary = Color(0xFFFFFFFF)
val GreenTertiaryContainer = Color(0xFFBCEBEC)
val GreenOnTertiaryContainer = Color(0xFF002021)
val GreenError = Color(0xFFBA1A1A)
val GreenOnError = Color(0xFFFFFFFF)
val GreenErrorContainer = Color(0xFFFFDAD6)
val GreenOnErrorContainer = Color(0xFF410002)
val GreenBackground = Color(0xFFFDFDF5)
val GreenOnBackground = Color(0xFF1A1C18)
val GreenSurface = Color(0xFFFDFDF5)
val GreenOnSurface = Color(0xFF1A1C18)
val GreenSurfaceVariant = Color(0xFFDFE4D6)
val GreenOnSurfaceVariant = Color(0xFF43483E)
val GreenOutline = Color(0xFF73796D)
val GreenOutlineVariant = Color(0xFFC3C8BB)
val GreenScrim = Color(0xFF000000)
val GreenInverseSurface = Color(0xFF2F312C)
val GreenInverseOnSurface = Color(0xFFF1F2EA)
val GreenInversePrimary = Color(0xFF9CD67D)

// Dark scheme
val GreenPrimaryDark = Color(0xFF9CD67D)
val GreenOnPrimaryDark = Color(0xFF0A3900)
val GreenPrimaryContainerDark = Color(0xFF1F5207)
val GreenOnPrimaryContainerDark = Color(0xFFB7F397)
val GreenSecondaryDark = Color(0xFFBCCBB0)
val GreenOnSecondaryDark = Color(0xFF273421)
val GreenSecondaryContainerDark = Color(0xFF3D4B35)
val GreenOnSecondaryContainerDark = Color(0xFFD8E7CB)
val GreenTertiaryDark = Color(0xFFA0CFD0)
val GreenOnTertiaryDark = Color(0xFF003738)
val GreenTertiaryContainerDark = Color(0xFF1F4E4F)
val GreenOnTertiaryContainerDark = Color(0xFFBCEBEC)
val GreenErrorDark = Color(0xFFFFB4AB)
val GreenOnErrorDark = Color(0xFF690005)
val GreenErrorContainerDark = Color(0xFF93000A)
val GreenOnErrorContainerDark = Color(0xFFFFDAD6)
val GreenBackgroundDark = Color(0xFF1A1C18)
val GreenOnBackgroundDark = Color(0xFFE2E3DB)
val GreenSurfaceDark = Color(0xFF1A1C18)
val GreenOnSurfaceDark = Color(0xFFE2E3DB)
val GreenSurfaceVariantDark = Color(0xFF43483E)
val GreenOnSurfaceVariantDark = Color(0xFFC3C8BB)
val GreenOutlineDark = Color(0xFF8D9286)
val GreenOutlineVariantDark = Color(0xFF43483E)
val GreenScrimDark = Color(0xFF000000)
val GreenInverseSurfaceDark = Color(0xFFE2E3DB)
val GreenInverseOnSurfaceDark = Color(0xFF2F312C)
val GreenInversePrimaryDark = Color(0xFF386A20)
